In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

pd.set_option("display.max_columns", None)

In [2]:
data=pd.read_csv(r"framingham.csv")
data.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [4]:
data2=data.fillna(data.median())

In [5]:
data2.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [6]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4238 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4238 non-null   float64
 5   BPMeds           4238 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4238 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4238 non-null   float64
 13  heartRate        4238 non-null   float64
 14  glucose          4238 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [7]:
data2.corr()

male       age  education  currentSmoker  cigsPerDay  \
male             1.000000 -0.028979   0.017205       0.197596    0.315630   
age             -0.028979  1.000000  -0.163547      -0.213748   -0.191847   
education        0.017205 -0.163547   1.000000       0.018273    0.007618   
currentSmoker    0.197596 -0.213748   0.018273       1.000000    0.760239   
cigsPerDay       0.315630 -0.191847   0.007618       0.760239    1.000000   
BPMeds          -0.051545  0.120955  -0.010365      -0.048358   -0.044675   
prevalentStroke -0.004546  0.057655  -0.035150      -0.032988   -0.032244   
prevalentHyp     0.005313  0.307194  -0.081021      -0.103260   -0.065046   
diabetes         0.015708  0.101258  -0.038136      -0.044295   -0.036150   
totChol         -0.069549  0.260105  -0.022364      -0.046466   -0.026976   
sysBP           -0.035989  0.394302  -0.128273      -0.130230   -0.088375   
diaBP            0.057933  0.206104  -0.061719      -0.107746   -0.056687   
BMI              0.081653  0.135174  -0.135501      -0.167161   -0.092211   
heartRate       -0.116621 -0.012848  -0.053683       0.062330    0.073853   
glucose          0.010073  0.117788  -0.033982      -0.055177   -0.056863   
TenYearCHD       0.088428  0.225256  -0.053383       0.019456    0.058859   

                   BPMeds  prevalentStroke  prevalentHyp  diabetes   totChol  \
male            -0.051545        -0.004546      0.005313  0.015708 -0.069549   
age              0.120955         0.057655      0.307194  0.101258  0.260105   
education       -0.010365        -0.035150     -0.081021 -0.038136 -0.022364   
currentSmoker   -0.048358        -0.032988     -0.103260 -0.044295 -0.046466   
cigsPerDay      -0.044675        -0.032244     -0.065046 -0.036150 -0.026976   
BPMeds           1.000000         0.114609      0.258697  0.051394  0.078578   
prevalentStroke  0.114609         1.000000      0.074830  0.006949  0.000123   
prevalentHyp     0.258697         0.074830      1.000000  0.077808  0.163054   
diabetes         0.051394         0.006949      0.077808  1.000000  0.040117   
totChol          0.078578         0.000123      0.163054  0.040117  1.000000   
sysBP            0.251503         0.057009      0.696755  0.111283  0.207522   
diaBP            0.192356         0.045190      0.615751  0.050329  0.163888   
BMI              0.099584         0.024265      0.300510  0.086025  0.114811   
heartRate        0.015142        -0.017674      0.147196  0.048996  0.090537   
glucose          0.049124         0.018722      0.083571  0.606493  0.045559   
TenYearCHD       0.086417         0.061810      0.177603  0.097317  0.081566   

                    sysBP     diaBP       BMI  heartRate   glucose  TenYearCHD  
male            -0.035989  0.057933  0.081653  -0.116621  0.010073    0.088428  
age              0.394302  0.206104  0.135174  -0.012848  0.117788    0.225256  
education       -0.128273 -0.061719 -0.135501  -0.053683 -0.033982   -0.053383  
currentSmoker   -0.130230 -0.107746 -0.167161   0.062330 -0.055177    0.019456  
cigsPerDay      -0.088375 -0.056687 -0.092211   0.073853 -0.056863    0.058859  
BPMeds           0.251503  0.192356  0.099584   0.015142  0.049124    0.086417  
prevalentStroke  0.057009  0.045190  0.024265  -0.017674  0.018722    0.061810  
prevalentHyp     0.696755  0.615751  0.300510   0.147196  0.083571    0.177603  
diabetes         0.111283  0.050329  0.086025   0.048996  0.606493    0.097317  
totChol          0.207522  0.163888  0.114811   0.090537  0.045559    0.081566  
sysBP            1.000000  0.784002  0.325161   0.182143  0.135136    0.216429  
diaBP            0.784002  1.000000  0.376623   0.181257  0.059042    0.145299  
BMI              0.325161  0.376623  1.000000   0.067520  0.082219    0.074217  
heartRate        0.182143  0.181257  0.067520   1.000000  0.087315    0.022857  
glucose          0.135136  0.059042  0.082219   0.087315  1.000000    0.121277  
TenYearCHD       0.216429  0.145299  0.074217   0.0228

In [8]:
y=data2["TenYearCHD"]
X=data2.drop(columns=["TenYearCHD"])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='lbfgs', max_iter=5000).fit(X_train, y_train)

In [11]:
clf.score(X_train,y_train)

0.852765058119056

In [12]:
clf.score(X_test,y_test)

0.8620443173695497

In [13]:
y_pred=clf.predict(X_test)

In [14]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred))

0.37142385845614484

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1185,    9],
       [ 184,   21]], dtype=int64)

In [16]:
from sklearn.tree import DecisionTreeClassifier
clf2=DecisionTreeClassifier().fit(X_train, y_train)

In [17]:
clf2.score(X_train,y_train)

1.0

In [18]:
clf2.score(X_test,y_test)

0.7448177269478199

In [19]:
y_pred2=clf2.predict(X_test)

In [20]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred2))

0.5051556918932817

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred2)

array([[992, 202],
       [155,  50]], dtype=int64)

In [22]:
from sklearn.ensemble import RandomForestClassifier
clf3=DecisionTreeClassifier().fit(X_train, y_train)

In [23]:
clf3.score(X_train,y_train)

1.0

In [24]:
clf3.score(X_test,y_test)

0.7548248749106504

In [25]:
y_pred3=clf3.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred3))

0.4951516182840863

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred3)

array([[999, 195],
       [148,  57]], dtype=int64)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
clf4=KNeighborsClassifier().fit(X_train, y_train)

In [29]:
clf4.score(X_train,y_train)

0.857344135258894

In [30]:
clf4.score(X_test,y_test)

0.8377412437455325

In [31]:
y_pred4=clf4.predict(X_test)

In [32]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred4))

0.4028135502369148

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred4)

array([[1151,   43],
       [ 184,   21]], dtype=int64)